                                                        ** Hw4-MohammadReza Arani-Q2 **


In [61]:
import numpy as np
import matplotlib.pyplot as plt
# we want to implement MAXnet:

def activation_func(X):
    a=X
    if X < 0:
        a=0
    return a


def MAXNET_1(X,eps,verbose):
    Final=0
    # first initialize weight matrix:
    W=np.ones((X.shape[0],X.shape[0]), int)
    W=-W*eps
    np.fill_diagonal(W, 1)
    # Then we need to use a temp variable such as : a in first epoch
    epch=1
    a=np.copy(X)
    while(1):
        if(np.sum(a==0) >= len(a)-1):
                    break
        Vector_activation_func=np.vectorize(activation_func)
        a=Vector_activation_func(W.dot(a.T))
        a_new=np.around(a, 3)

        if(verbose==1):
            print('Epoch: '+str(epch)+' : New a = : \n',a_new)
        epch=epch+1

    print('Final Epoch : '+str(epch)+' : Final a = :\n ',a_new)            
    Final = (X[a != 0 ])

    return Final    









In [42]:
# First Given Input Vector:
X=np.asarray([1.2, 1.1 , 0.5 , 1.5 , 1.13 , 0.8])
eps=0.13
Final = MAXNET_1(X=X,eps=eps,verbose=1)
print("The maximum value in this array is: ", Final)

Epoch: 1 : New a = : 
 [0.5 0.4 0.  0.9 0.5 0.1]
Epoch: 2 : New a = : 
 [0.3 0.1 0.  0.7 0.3 0. ]
Epoch: 3 : New a = : 
 [0.2 0.  0.  0.6 0.2 0. ]
Epoch: 4 : New a = : 
 [0.1 0.  0.  0.5 0.1 0. ]
Final Epoch : 5 : Final a = :
  [0.  0.  0.  0.5 0.  0. ]
The maximum value in this array is:  [1.5]


In [45]:
#  We can Consider multiple Conditions and use the same function we ever used above:
X=np.asarray([1.3, 1.1 , 0.5 , -1.5 , 1.13 , -0.8])
X1=X
print("Using MAXNET for X : ")
eps=0.13
Final1 = MAXNET_1(X=X1,eps=eps,verbose=1)
print("The maximum value in this array is: \n \n \n", Final1)



Using MAXNET for X : 
Epoch: 1 : New a = : 
 [1.2 1.  0.3 0.  1.1 0. ]
Epoch: 2 : New a = : 
 [0.9 0.7 0.  0.  0.8 0. ]
Epoch: 3 : New a = : 
 [0.7 0.5 0.  0.  0.6 0. ]
Epoch: 4 : New a = : 
 [0.6 0.3 0.  0.  0.4 0. ]
Epoch: 5 : New a = : 
 [0.5 0.2 0.  0.  0.3 0. ]
Epoch: 6 : New a = : 
 [0.4 0.1 0.  0.  0.2 0. ]
Epoch: 7 : New a = : 
 [0.4 0.  0.  0.  0.1 0. ]
Final Epoch : 8 : Final a = :
  [0.4 0.  0.  0.  0.  0. ]
The maximum value in this array is: 
 
 
 [1.3]


In [62]:
X=np.asarray([1.2, 1.1 , 0.5 , -1.5 , 1.13 , -0.8])
X1=-X
print("Using MAXNET for -X : ")
eps=0.13
Final2 = MAXNET_1(X=X1,eps=eps,verbose=1)
print("The maximum value in this array is: \n \n", Final2)

Using MAXNET for -X : 
Epoch: 1 : New a = : 
 [0 0 0 1 0 1]
Epoch: 2 : New a = : 
 [0 0 0 0 0 0]
Final Epoch : 3 : Final a = :
  [0 0 0 0 0 0]
The maximum value in this array is: 
 
 []


In [93]:
TotalMax=max([Final1,Final2])
print('Maximum value for Absolute value is : ' ,TotalMax)

Maximum value for Absolute value is :  [1.5]


<ipython-input-93-d7336904bd87>:1: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  TotalMax=max([Final1,Final2])


In [74]:
X=np.asarray([1.2, 1.1 , 0.5 , -1.5 , 1.13 , -0.8])
X1=-X

Final=0
# first initialize weight matrix:
W=np.ones((X1.shape[0],X1.shape[0]))
W=-W*eps
np.fill_diagonal(W, 1)
# Then we need to use a temp variable such as : a in first epoch
epch=1
a=np.copy(X1)
while(1):
        Vector_activation_func=np.vectorize(activation_func)
        a=Vector_activation_func(W.dot(a.T))
        print(W.dot(a.T))
        a_new=np.around(a, 3)
        print(a)

        if(1):
            print('Epoch: '+str(epch)+' : New a = : \n',a)
        epch=epch+1
        if(len(np.unique(a))<len(a)):
              print('Final Epoch : '+str(epch)+' : Final a = :\n ',max(X1[a != 0 ]))            
              Final = max(X1[a != 0 ])
              break
        if(np.sum(a==0) >= len(a)-1):
                print('Final Epoch : '+str(epch)+' : Final a = :\n ',a)            
                Final = (X1[a != 0 ])
                break

 
# print(X1)
# print(a)
# print(epoch)
# print(np.sum(a==0)<len(a)-1)
# print( activation(w.dot(a.T)))
# print( Vector_activation_func(w.dot(X1.T)))


[-0.26 -0.26 -0.26  0.87 -0.26  0.87]
[0 0 0 1 0 1]
Epoch: 1 : New a = : 
 [0 0 0 1 0 1]
Final Epoch : 2 : Final a = :
  1.5
